trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'run'
    projects: './src/Tests/Tests.fsproj'

- task: PublishTestResults@2
  displayName: "Publish Test Results"
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TestResults*.xml'

- task: CmdLine@2
  displayName: "Build Speaker Shuffler"
  inputs:
    script: |
      dotnet tool install fake-cli -g
      fake build --target build
    failOnStderr: true

- task: PublishBuildArtifacts@1
  displayName: "Publish artifacts to release"
  inputs:
    PathtoPublish: './src/Client/deploy/'
    ArtifactName: 'drop'
    publishLocation: 'Container'
